services:
  - type: web
    name: moxiskincare
    env: docker
    dockerfilePath: demo/Dockerfile
    plan: free
    envVars:
      - key: PORT
        value: "8080"
      - key: MYSQL_URL
        value: "jdbc:mysql://mysql-378386e7-utp-7ece.g.aivencloud.com:27025/defaultdb?ssl-mode=REQUIRED"
      - key: MYSQL_USERNAME
        value: "avnadmin"
      - key: MYSQL_PASSWORD
        value: "AVNS_Dye1oqZxvppeogu9GU|v"
