services:
  - type: web
    name: moxiskincare
    env: docker
    dockerfilePath: demo/Dockerfile
    plan: free
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://mysql-378386e7-utp-7ece.g.aivencloud.com:27025/defaultdb?ssl-mode=REQUIRED&allowPublicKeyRetrieval=true
      - key: SPRING_DATASOURCE_USERNAME
        value: avnadmin
      - key: SPRING_DATASOURCE_PASSWORD
        value: S